
--[[

Information:

For the text you want to find tags in
simply sill the text section below.
For the tags that you want to try and find
within the text, fill out the tags section
below the text section.
If you would like to add a new item,
make sure and use a comma at the end of the line.
If you forget this, you will get an ERROR

Like this -->    "newtag",
NOT THIS  -->    "newtag"

You may run into issues if the word is plurarl,
for this, fill out the esExceptions area for any tags
that you have that use "es" at the end of the word.
This program is still very much a work in progress
BUT it is functional.

be aware for words like
that need the letter y to become singular,
such as "Activities", "agencies" ... ETC.
you will have to MANUALLY fix these for now.

]]--

--- SETTINGS YOU CAN CHANGE ARE BELOW ---

-- If you would like to change you the tags are seperated
-- (if you use "\n", it will show each tag on a new line)
SEPARATOR_CHARACTER = "&"

esExceptions = {
  "wharves",
  "Vehicles",
}

text = "Tom Hungate: Rolling.Robert Franklin: Okay. My name is Robert Franklin. I am conducting an oral history interview with Keith Klein on February 7th, 2016. The interview is being conducted on the campus of Washington State University Tri-Cities. I will be talking with Keith about his experiences working at the Hanford Site. And for the record, can you state and spell your full name for us?Keith Klein: Keith Klein. K-L-E-I-N.Franklin: Okay. And K-E-I-T-H?Klein: K-E-I-T-H, yeah.Franklin: Okay, great. Tell me how and why you came to work at the Hanford Site.Klein: Well, I suppose it started as—born in the early ‘50s, and at that time, atomic energy was the stuff of comic books and intrigue and power. It was, you know—whenever the planet was threatened by alien beings, they’d always convene a meeting of the Atomic Energy Commission. So I think in the back of my mind, I always had an inkling that I’d end up somehow dealing with atomic energy. The path that got me here was actually as an Atomic Energy Commission intern in the early ‘70s. One of my assignments as an intern was out here doing FFTF construction, I think in ’73. After that, a series of assignments, most back at headquarters dealing with all aspects of the fuel cycle. Mid ‘90s, I was dispatched to Rocky Flats, and that’s where I gained experience dealing with plutonium and contaminated facilities and the work force and this kind of the field experiences as a deputy manager out at Rocky Flats. One of the obstacles to getting Rocky Flats cleaned up was getting rid of the transuranic waste. So I ended up getting dispatched down to Carlsbad, New Mexico for a six-month stint with the assignment of getting it open and recruiting a permanent manager. Opening WIPP had eluded a number of people and brought in lawsuits. There were a lot of different combination of technical issues, operational issues, regulatory, political, perception, communications issues—you name it. But I guess I impressed the secretary with that assignment, and next thing you know, he asked me to come out here to Richland. That was in 1999. So I came out here as a manager of the Richland Operations Office then and was here until I retired from federal service in 2007.Franklin: Great. Just for those who might not know, could you say what WIPP stands for and what its mission was?Klein: WIPP is the Waste Isolation Pilot Project, and it was the first deep geologic disposal facility in the—well, in the world, really. It’s in a geologic formation, about a half-mile under in salt beds that are several hundreds of millions of years old and have been—just their very existence shows a lack of moving water, because salt being soluble. And of course disposing of nuclear waste and particularly of things—plutonium-bearing waste, transuranic waste falls in that category. Lot of folks afraid about transportation and is it going to leak out and so forth. But the community there was actually very supportive. The scientific community was as well. But of course there was a lot of—you know, this is falling on the heels of nuclear power, a lot of opponents of nuclear power. It seemed like we’re similarly opposed to solving the waste problem. So it had some similar characteristics as the challenges being faced up here. But that was a very big deal for those of us in the nuclear waste community. It was recently shut down for some operational issues. And when it shuts down it shuts down for a few years. But it was key to emptying out this category waste called transuranic waste from sites around the country including here at Hanford and the national laboratories.Franklin: When you came out in the early ‘70s as an intern for FFTF construction, what did you do?Klein: Well, it was FFTF construction. Actually first assignment was dealing with electrical systems then. I was assigned to—it was a Bechtel Corporation doing work out there in the field. I was being mentored by a fellow that was actually in a responsible for the crafts, pulling wire and routing things. So you know that was all part of giving us on-the-ground experience. And this in particular was construction. Later went to a Westinghouse subsidiary that was placing the large vessels, setting the pumps and the heat exchangers and that sort of thing. It was an incredible amount of stainless steel. And quality assurance, obviously, building a reactor is very important. Had to have good records and had to know that things in fact were welded like they’re supposed to be, tested like they’re supposed to be and so forth. And it—of course—you know, then I was part of the AEC Breeder Reactor Program and I think that was what really attracted me to the Atomic Energy Commission, is the idea that a source of energy could make more fuel than it used. And it seemed environmentally benign at the time. I still happen to believe it’s one of the more benign forms of energy, but it’s obviously been beset with a number of challenges in terms of the times—and this comes back to Hanford, actually. The time it takes to do things now and the number of layers and checks and so forth. In the commercial nuclear business, time is money. And the more time it takes, the more costs. And then things getting held up in the regulatory process with interveners, it basically got priced out of the market and became uneconomical. It had also gotten very complicated at the time, and that’s another example. You start adding layers of safety and things like that, you can end up—things getting more complicated and difficult to analyze and manage and deal with. So it kind of collapsed under its own weight there for a while. But there is a new generation of reactors that are coming that are more inherently safe and simpler in a lot of respects. So I think there’s still some hope out there for sources of electrical energy that, in my mind, can be very benign.Franklin: Mm-hm. Thank you. So you came to RL—Richland—in ’99, then, and you were the site—the DOE site manager.Klein: Correct.Franklin: For the Hanford unit. Can you talk about some of the progress you made in that position, but also maybe some of the setbacks as well? Because that’s during this kind of shift into this more modern phase of cleanup, right, where most of the production and reprocessing of fuels had stopped by that point.Klein: That’s a huge topic, Robert.Franklin: Sure.Klein: But it’s actually one I love to talk about because it was indeed a very daunting challenge. I understand you’ve interviewed Mike Lawrence and he signed a compliance agreement out here, the Tri-Party Agreement. But then he left and left it to others to implement that and get the work done. So he made the commitments and everyone else was kind of left holding the bag. John Wagner, I think did his best to get the ball rolling, but I think during that time there was just a lot of norming and forming and trying to figure out things. There wasn’t a whole lot of on-the-ground progress. I learned a lot at Rocky Flats and at WIPP about what it takes to get work done in these kind of environments. That included both technically and in terms of dealing with the workforce and dealing with the contracts. You know, the people that do the real work here are really contractors to DOE. And depending on how the contracts are written and things are incentivized and how much—just the whole dynamic between receiving the money—you have to go out and get the money from Congress, so you have to convince them that you have a plan, you know what you’re doing, you can deliver, that you’re investment grade. And then you have to deliver, because if you don’t, the money will dry up and lots of other problems. So giving this cleanup some focus, some momentum and just making it manageable, if you will, was one of the biggest challenges. Technically, there were two urgent risks—well, there were actually three urgent risks at the time. Of course the high-level waste that I think everybody knows about. But we had about 18 tons of plutonium-bearing materials that were unstable. These were things that when they shut down after the Cold War were left in various forms: alloys, residues, oxides, pure metal. And plutonium can be very reactive and exothermic. So it really needs to be stabilized, lest your—you have some real problems. Recall high school chemistry, you put a little sodium in the water—it’s that type of thing. So dealing with the plutonium—and again, I had the experience there with Rocky Flats—was a second urgent priority. And the third one was the spent fuel that was left in the K Basins. There were about 2,000 tons. That was about 80%, 90% of the DOE inventory that was left in the K Basins. This fuel was prone to oxidizing dissolving. And as a result of that, just deteriorating. So it was losing its integrity and creating a lot of sludge on the bottom. So even the act of moving it would create these clouds and you couldn’t see. The Site had been experimenting with different things to try to package up and dry out this—and stabilize this spent fuel so it could be stored in a dry, inert, stable, stable environment. So that was a second major challenge. And then of course there’s all this contaminated groundwater underlying the Site. Billions of gallons that had been dumped into the soil. You know, the soil here is something called a vadose zone where it’s got this dry sand and gravel mixtures and then there’s—can be basalt layers under that that are relatively impermeable, and you know, the water table that’s about where the Columbia River level is. So the center portion of the Site is built up. But long story short, waste in both liquid forms and then solid forms of waste have been buried in several hundred sites around the Hanford Site. So figuring out what we’re going to do with all those waste sites and with the contaminated groundwater was another set of challenges. And then of course there were, depending on how you count them, 700, 1,500 contaminated buildings out there that needed to be dealt with. This coupled with—right when I came, a legislation had been passed setting up a separate office of river protection to deal specifically with the high-level waste and the high-level waste tanks. So part of my job was helping to get that set up and transferred. Dick French was my counterpart dealing with that. The national lab, PNNL, was also actually under the Richland Operations Office at that time, but after a couple years it was decided similarly that the office of science—you know, it’s such a different focus that it was better off separated out. And from my standpoint, these were all good things, because there’s plenty of challenges to go around. So when I came, I guess my biggest challenges were how do you help manage, mobilize, organize efforts to get confidence that you have a plan for dealing with these things. We had these regulatory commitments, but it’s people that clean these things up. It’s not paper. You can sign anything you want; it doesn’t mean it’s going to happen. So this kind of comes down to contracts, understanding the workforce, what motivates them, and basically how to enable them. So my job is one of enabling. I mean, there’s so many smart people out here, it’s intimidating. And impressive and inspiring. And given the latitude, they’ll figure out how to do things. You compare when I came here it was different than it is even now, what, 16, 18 years later. But when I came here compared to like the ‘40s, a world of difference in terms of what it took to get work done. In the ‘40s, they could learn by doing, experiment, play with things, and they didn’t have to get multi layers of permission, or—they didn’t have emails or cell phones or computers. I mean, it was slide rules and hand-written notes and so forth. Which comes back to just how amazing they were. How creative and innovative. Of course, it was under a wartime environment. But contrast that, when I came here—a lot of different regulatory structures put in place—something called the Defense Nuclear Facilities Safety Board to oversee DOE. The Atomic Energy Commission was self-regulating. And when environmental laws were passed, which has led to the Tri-Party Agreement, the Department of Energy was out of compliance with a number of these national laws, like the Resource Recovery—RCRA—and the Comprehensive Environmental Liability—CRCLA. So this compliance agreement, the Tri-Party Agreement was basically—this is how DOE was going to come into compliance with these things. Of course, there’s money that’s associated with that. DOE, like other agencies, lives on an annual budget. So you can’t get multi-year appropriations; you never really know how much you’re going to get from year to year. So to make commitments hoping you’ll get the money is part of the whole dynamic of getting work done here. But back to what it takes to get work done. It’s understanding these different laws and regulations. In my mind, I was fortunate, then, that I had good relationships back at headquarters and the trust and confidence of the leadership. So I was able to basically authorize more things on my signature based on my discretion than, certainly, what can be done today. Unfortunately with problems, you get more oversight and more second guessing and so forth. So it’s kind of success-begets-success. But in any event, my focus—and before you can clean up the buildings, you have to deal with the urgent priorities first: things that can go bump in the night. And again it comes back to the top three at the time were high-level waste and the plutonium, and the spent fuels. So the focus was really on the plutonium and spent fuel until you can get these things out of the different buildings, you can’t take down the buildings, that’s—stabilizing these things more important than—you know, the ground water was contaminated. I mean, the contamination was spreading, but you had to remove the sources, otherwise you’re continuing to feed—you can continue to clean up the groundwater, but there’s still stuff coming in, then you’re just kind of halting some progression but not really cleaning it up. So dealing with these different sources was the focus. But long story short, we had some brainstorming sessions with all the contractor heads, KEA, you know, folks that were working for me—how can we make this a simple, compelling, understandable vision? Make this, our task, more manageable? And what we came up with was basically featured three things. We came to call it the river, the plateau and the future. And said, our job is going to be to transition the central part of the Site into a long-term waste management area. The central part of the Site is where the high-level waste tanks are, the reprocessing canyons, a lot of these burial grounds. I mean, we were going to be here for a long time. And that’s also the stuff that’s farthest away from the river. So if you can sort of encapsulate and stop the hemorrhaging there, then kind of in a triage approach, then, that gives you—allows you to start cleaning up the rest. The second part was restoring the river corridor. And there the idea was to clean this up as good as is practical as we could and to make it available for other uses. So these are the reactors along the river, the other waste sites, burial grounds, the areas around the 300 Area where all the research is taking place and things like that. And the third part, the future, was—I guess I viewed this whole challenge out here as one of managing change and transition. And considering that we have 10,000 folks working out here, they need a future. It’s hard enough to ask someone to work themselves out of a job, but to work themselves out of a job without the prospect of other jobs, so—and that’s not something the DOE, the Atomic Energy Commission or others had a whole lot of experience at or are very good at. We’re a scientific and technical community. And most of us, myself included, is engineers. We go into these disciplines because we like numbers and quantities and we’re typically introverts and that sort of thing. So dealing with something as amorphous as the future is tough. But we convinced ourselves it was important and we had all these resources like the Pacific Northwest National Laboratory and university systems and all these smart, talented people. There’s no reason why the things we’re learning here, lessons learned and businesses that could develop around here couldn’t be provided for a good socioeconomic environment here, too. And I think the Department of Energy and its predecessors always wanted to be a good community citizen. So just scrubbing out all the molecules but leaving this place an economic ghost town is not the right thing to do. Certainly, we want to get it as clean as we can, but you want to leave the community whole. And it comes back to the sacrifices that were made here going back to the tribes and the folks that were evicted in order to do this and the people that lost their lives helping to build the facilities and operate the facilities in the early years to produce the weapons material. Certainly the communities paid a price here. So the river, the plateau, and the future was kind of our mantra, and that’s how we organized things. Tried to fashion over the years that followed contracts that did that. But in any event, what I did was I sold—as for meeting with Doc Hastings, he was the congressman at the time. Sat down with him. I remember it very well, I was still—had become a—because of Rocky Flats and Waste Isolation Pilot Plant—I had some experience dealing with elected officials and high level stuff, but it’s still intimidating. You know, it’s like, I’m a freaking engineer. So but went to him with—at his office over in Pasco and laid this out. And he liked it, and we had some very good discussions and a rapport. But he lives across the river from the 300 Area, is where his house is. So he looks down, and he can actually see a lot of these things. And of course he’s committed to the community and Hanford and he wanted to give me the best shot possible as well. And I should say, too, due to my homework before I came in here, I learned about folks like Sam Volpentest and Bob Ferguson and I went around and met them and got their ideas, perception of things, and how things work. So I think I was fortunate, had a lot of good support from different corners. Doc went to bat for us, as did the senators, for the funding. They’ve been great supporters here, appreciative of the history and the challenges that remain. We put in place contracts. I brought a contract type they used at Rocky Flats successfully that’s different than the conventional contracts that the Atomic Energy Commission was used to operating under. The traditional contracts are management and operating contracts. And in that kind of contract, it’s for a certain period of time and the contractor’s pretty much graded by how their DOE counterparts felt about how they were doing. And it was a lot of one-to-one counterparts with the contractors doing whatever DOE said at any particular time. So, it can work well when you’re in kind of a steady environment in a production mode, like churning out nuclear weapons material and operating. But at Rocky Flats what we learned is you need a lot more incentive to be creative and innovative. What worked there was having an agreement with the contractors and the contract type and the regulators about, this is the scope of work that’s going to get done, and as long as we stay within this box, basically—you know, leave us alone. And that was my philosophy in this contract that’s called a cost-plus-incentive-fee contract, CPIF, versus MNO which is a cost-plus-award fee. And the amount of money the contractor makes is tied to how well they do this tangible piece of work that you can actually see and feel. So we have an official government estimate that this is how long it should take based on our historical experience; this is how much it should cost. So every dollar you save bringing that in sooner and earlier, you get to save 30 cents on that dollar. So when you’re talking about contracts that cover, you know, five- to ten-year period, you’re talking about potentially a couple hundred million dollars in fees on the table there. Well, at Rocky Flats, what we learned is, particularly the contractors can share that with the employees, that they can get quite creative about how to do things. And they are able to learn by doing. You know, the envelope is a safety envelope; you can’t do anything unless you know it’s safe. So that’s where we focused our attention, is making sure we had a good safety basis and watching that through facility reps and other things. But basically, not trying to micromanage or giving them the freedom, as much as we could, to do things. And having a very good scope. So that’s what we put around the river corridor contract. The idea there is we’re going to blitz the river corridor. And we need this tangible progress, too, to further build confidence that we can do this. Of course, you can’t demolish buildings and excavate sites unless you’ve got something to do with the waste that’s coming out. So that comes back to things like ERDF and the different disposal grounds in the middle of the site—the energy—Environmental Restoration Disposal Facility—huge facility in the center of the site. So this whole thing becomes a huge chess game of sorts where the different pieces are the money and the contracts and the people and the labor agreements and the different technical pieces that have to fall in sequence before you can do things. And in some way, the icing on the cake is actually taking down the buildings. Because by that time, you’ve had to take the materials out. And you can’t take the materials out unless there’s something you can do with them. So whether there’s plutonium and having the equipment in place to stabilize them and then package it and put it somewhere. That’s basically the plan we had: the river, the plateau and the future. And I think the results, I’m pretty proud, speak for themselves. We packaged up all that spent fuel, got it off the river, from out of the K Reactors into the central part of the plateau. We got all the plutonium stabilized. And that ended up being able to—my successor able to ship that actually offsite to Savannah River. And put in place the river corridor contract, which I think has been pretty widely acclaimed and recognized as being successful. And it meant a lot of good things are happening. The folks dealing with high-level waste and the Waste Treatment Plant I think have had some different kinds of challenges and still dealing with a lot of that. But I think you see excellent progress on the rest of the Site.Franklin: I was wondering if you could speak about the challenge of vitrification as a—I mean, it’s a proposed way to isolate and deal with the waste and it’s been successful at other sites, but seems to have hit snags at Hanford.Klein: Well, this was not my territory.Franklin: Okay.Klein: I know a fair amount about it, so I’m tempted to give you opinion. But I did not have responsibility for that, and so—Kevin Smith is the current Office of River Protection manager and he’d be a better one to talk to about that. But vitrification in general was a form preferred by the state and others for stabilizing some components of the waste out there that’s very highly radioactive. It’s interesting—back in the day, some of the components in these tanks that generate the most heat are strontium and cesium: fission products, versus the actinides. The actinides being plutonium, uranium, those type of things. And there’s not a whole lot of that in this high-level waste. But in the old days, they started taking out the cesium and the strontium so the tanks weren’t generating as much heat so they could put more waste in. And we put—before my time, they put the strontium and cesium into capsules. And they’re stored in a water pool up—attached to one of their processing facilities and that was under my purview. Now the process moving that to dry storage. And I only say that because, you know, in my mind, there are alternative forms for managing these different wastes that they can be used. And with fission products, 30-year half-life, rule of thumb is if ten half-lives—these things reduce to a millionth their radioactivity or less, 10-6, and basically are innocuous at that time. So thirty years, half-life of ten years, that’s 300 years. In geologic time, that’s nothing. So do you really need geologic disposal for things with fission products with 30-year half-lifes? And if you don’t need geologic disposal, do you really need to vitrify the wastes and put them into these glass waste forms? I mean, basically what’s attractive about glass is it’s not as susceptible to dissolution and water and dissolving. So things can stay pretty much contained, is the thought. But even these high-level waste logs, they’re just going into dry storage anyway. You know, I’m a proponent, I guess, for a lot of these different wastes, that dry storage, I think, is the most economical, efficient, and—I think there’s a reasonable chance our civilization will stay intact for 300 years. You can put these things in dry storage casks and things like that, they’re basically tamper-proof and they cool themselves. It’s just keeping people away from them. I mean, I can talk more about vitrification if you really want, but like I said, it’s really not my bailiwick.Franklin: No, that’s fine. So you said your three major challenges were dealing with high-level waste, dealing with unstable plutonium-bearing materials and then the spent fuel. Klein: High-level waste was assigned to the separate office, so that really wasn’t my—Franklin: Oh, okay, so—Klein: --biggest challenge. So it was plutonium and the spent fuel were the two urgent priorities. But the third is really getting on with the cleanup and giving the whole cleanup some momentum and direction and some legs.Franklin: What do you see as the future of Hanford? Because the focuses of the river, the plateau and the future. And the river and plateau seem to have these concrete goals applied to them. The future does seem harder to diagnose or kind of see, because eventually there is an idea that cleanup will be performed. And then so what do you think the future of the Tri-Cities holds after the danger’s mitigated?Klein: Science, technology, engineering and math. I think this is, at its heart, a STEM community. And I think that we are very well-suited to grow that identity. We have a great STEM education that’s getting recognized nationwide [UNKNOWN] leading that. We have, I think, STEM employment opportunities. One of the things—my interests after retiring is running something called Executive Director Tri-Cities Local Business Association. And it’s looking at helping build local businesses with a high-tech nature that can help accommodate transition of employees. I’ve been active in promoting provisions in the DOE subcontracts that encourage the prime contractors to contract out more and better pieces of work to companies. So, I mean, I think there’s always been a good support for small businesses, but oftentimes that can be for janitorial supplies or this little thing, that little thing. There’s basically a huge workforce embedded—we call it in the fence—that does a lot of these other things. I’d like to see more, bigger, better chunks of that work able to go to local businesses that can then use that to develop their resumes. I mean, they’re highly incentivized to perform if—one, this is their backyard, their neighbors; two, you don’t get invited back to the party if you don’t do well. And they’re small and they’re very manageable. I think it would be very efficient. We have a number of examples of companies that have grown out of Hanford business or out of PNNL inventions or the expertise that people develop here that’s applicable to environmental challenges around the globe. So I think capitalizing on the lab and its high-tech things they do. We have BSEL right here and WSU Tri-Cities is a good example of kind of the collaborations. But PNNL is in a number of different sectors, and so the leveraging that more to help grow STEM businesses, employment opportunities, research opportunities I think is good. You’ve got the viticulture and the science of wines that is, I think, grown appreciation. Tourism, things like the Manhattan National Park, where people will come and see and appreciate the remarkable things that were done here. And the consequences, good and bad. But I mean it’s just—the stories to be told, people come here from around the world, I think, to see firsthand B Reactor and learn more about what that meant, what it took to get there. You’ve got the Reach National Monument, you have Ice Age Floods. There’s even STEM tourism. So you’ve got STEM education, STEM employment, STEM entrepreneurship. STEM tourism, I think, could really change—when people think of Hanford, instead of a stigma and high-level waste, oh my god, and the images that are conjured up there, I think are somewhat overblown. But instead of that, thinking of Hanford as science, technology, energy and math. This is the place to come to start a business, to get experience, to find good, smart people. I think it would do a good service for the community. And I think the national park would be one of the crown jewels in terms of STEM identity. Franklin: Great. Speaking of high-level waste, has most of the danger been mitigated, to your knowledge, of the waste that’s out onsite? Or where—yeah, that’s my question.Klein: The urgent risks have. I think, for the most part, the High Level Waste Tank have been interim stabilized, which means they’re—most of the things that are a threat of getting out and leaking, they basically got as much water, liquids, out of them as is possible in the single-shelled tanks. Leaks there, without a source of water, something to drive it further down into the water column or out, is mitigated. Double-shelled tanks are getting old and, of course, that’s a—had some leaks there. But even there, they’re double-shelled, so you can detect it and they can be emptied. Of course running out of space there. But the problem with nuclear waste, again, is until you know what you’re going to do with it, you can end up just moving it around. So the idea is you really need to put it in a better form and move it to someplace where it can be more easily managed or basically almost be semi-maintenance-free. We put a lot of stock into deep geologic repository, Yucca Mountain, that’s what we need to manage this high-level waste. But as I said before, I think, a lot of these can be managed quite safely for as long as may be necessary in dry storage still. So in terms of urgent risks, I think they’ve been for the most—mitigated. Now we’re dealing with more chronic, the longer-term risks and there, I think it’s a matter of being smart and getting a more productive. I think the red tape and the bureaucracy and the second-guessing, it’s almost become like a spectator sport with all the different oversight agencies and folks that are from King 5 over on the west side that seems to—and others, they’re really just focused on I’d say the things that can scare people or that might reflect badly on here but without appreciating it, I guess. I mean, there’s—yeah, there’s some mistakes that have been made, are being made, but the bulk of the people here that are good-hearted, well-intentioned, hard-working—you know, we live here, we drink the water here. If something was acutely dangerous, we’d know and we’d be able to deal with it. So I think things here are a lot safer than we appreciate.Franklin: Do you find that, in general, the public is misinformed about both the nuclear materials production process but also the waste and the dangers of nuclear waste?Klein: I would say, for the most part, the general public is apathetic about it. That there are segments of the public, the media, and others that—with different agendas, whether it be attention or profit or others, that put their own slant on it. But I think that with each new generation of people and understanding the atom that things are getting better. With radiation, you can measure it. It’s very easily detectable. Unlike gasses and chemicals and other things. We as a society put up, well, what are you going to do with the waste? Well, you look at the volumes of waste that are being involved and so forth, it’s really small. But we don’t seem to ask that same question about carbon dioxide and some of these others, yet we’re perfectly content to continue driving our cars and so forth. So I think there is a lack of perspective on these things. In some ways, it’s—the attention to them is important because they’re not going to just go away on their own. I mean, there’s still a lot of work that needs to be done and we need to have the resources to do it, and it’s kind of the squeaky wheel gets greased when it comes to budget things. But on the other hand, those things can get out of hand. So I don’t know what the public thinks, but I do have—[LAUGHTER]—I guess I’m an optimist at heart and think that each generation, like I said, is going to be smarter about—you know, what are the real hazards of these things and what really makes sense in terms of dealing with it? But one of my concerns is the less productive, the more inefficient we become: people with hands-on experience are retiring or dying. We can’t afford to lose that expertise. So I’m very much in favor of getting on with these things while we have these people around that know their way around and can deal with these things. Otherwise, we’re going to be wringing our hands and analyzing everything to death and actually doing less work. So that’s one of my biggest fears about all this stuff getting stretched out and prolonged.Franklin: When you were—it was eight years you were head of—for eight years you were head of DOE RL. How did you deal with the critics? Hanford detractors or critics of the cleanup operation. Were there protests in Richland? I know Mike Lawrence talked about protests, and I’m wondering if you—how did you deal with either the protests or media scrutiny of Hanford?Klein: You have to develop a thick skin. I mean, it still hurts. You feel it personally, you feel a disservice to all the folks that are working out here, putting their heart and soul into this. They get maligned so easily. How do you deal with it? It grates on you. It just kind of contributes to the stress. But it’s like, we’re all people with feelings and it’s—but the media typically focus on what’s going wrong and what’s sexy or what’s—get people’s attention, either sell viewership, readership, whatever. It just comes with the territory.Franklin: Interesting. Thank you. Do you—you mentioned something pretty interesting a few minutes ago and I kind of wanted to get your thoughts on it. I understand that you probably don’t have an intimate—you might not have an intimate knowledge of the oil and gas industry, but do you feel that the nuclear industry has more unfair restrictions on it than oil and gas does in terms of energy production? Because you mentioned that oil and gas production, people don’t think about their emissions from their car the same way they kind of get this emotional response to nuclear energy. And certainly oil and gas producers don’t have to plan for 50, 100, 3,000 years into the future for the byproducts of the product they sell. I’m wondering if you could ruminate on that a bit more, or if you feel like there’s an undue burden on the nuclear power industry that’s not on other forms of energy.Klein: I do think it has suffered unfairly for a number of reasons. Some of which I touched on before. I mean, I’m all for renewables, but I think they can only go so far. And it’s about the economics. I think the strength of our country is a lot about our economy. If you have cheap natural gas or—you know, the regulations on coal don’t take into account the cost of these different emissions, whether it’s CO2 or others, then I think those penalize the alternatives. Things like solar and wind have gotten tax breaks and different credits that I think have helped them come to market. Now you can get very inexpensive solar cells and things. And like I said, I’m all for using those where it makes sense. But from my standpoint, I think there’s still a need for some baseload. I think regionally distributed baseload, like small modular reactors, makes tremendous sense. So that you don’t have these vulnerable interconnected, largescale grids, but local communities could live on that, I think. In some areas of the world, they’re able to use the bypass, the residual heat, for steam, home heating and others. So I think, you look into the future, I think there could still be a very useful role for clean, safe, nuclear power without it being stymied by what about the nuclear waste? I think that can all be managed very well. So for future generations, I think—reducing dependence on fossil fuels and making the renewables—and I would consider nuclear power a renewable source—there’s lots of energy in those big atoms. It can and should be economical.Franklin: Great.Klein: If we get out of the way.Franklin: [LAUGHTER] I’d like to switch topics to the historic preservation angle of your work. And I’d like you to talk about your involvement with preservation and saving of B Reactor from—and where you started. I know it was originally scheduled to be remediated and that was postponed and then eventually, I think due to pressure from B Reactor Museum Association and other groups, it gained a different kind of status, landmark status and things. I was wondering if you could talk about your role in that effort.Klein: Well, you know, nine different reactors operating here along the Columbia River—really, nowhere else in the world is it like that. B Reactor being the first large industrial scale reactor in the world. The DOE office, back under the Office of Environmental Management. And their job is to clean up. DOE does have an historian. So you have a bureaucracy that’s basically goal in life is to remediate these sites and facilities and get the liabilities down, the mortgages down and so forth. There’s a lot of pressure to do that. We’re on a course of cocooning these various reactors, putting them into cheap-to-keep mode where basically you’ve removed all the ancillary facilities and reduced it down to a core building and sealed that up and basically [UNKNOWN] that went through all the regulatory processes. If we seal these up, put these into a mode that’s good for 50, 70 years, keep the critters and people out, and have monitors in it and then we’ll come back and the radiation levels will further decayed by then. And we can dispose of these, finally—these graphite blocks and cores. So we’re on a roll in terms of cocooning these reactors. But the—I guess the people—and you can’t help but work at these sites or go out to these facilities and not be in awe of the magnitude of what was accomplished out here from an engineering and scientific standpoint. I mean, to me, it was just remarkable and first time I went out to B Reactor, it—like most people, as nuclear engineers, it’s kind of like Mecca. It strikes you and it just—really, it just hits a chord emotionally. And certainly the folks at BRMA, the B Reactor Museum Association, and others felt—knew that. I think they were instrumental in raising some community consciousness about it. I had a person on my staff, Colleen French, who is now running the national park, who is communications, and she and I, basically, strategized as to how can we stop this freight train from running over B Reactor, considering that I had a mandate to proceed, basically, and cocoon it like the others. Folks on my staff, to be honest with you, were split. There were some people that saw it as an asset and others not—it’s a liability. Come on, get on with it. I lean towards the wanting to preserve it, and I guess, feel guilty almost taking it down. So Colleen and I strategized as to, how do we give this the best shot possible? So we went back and met with the DOE historian and talked to some others, and basically were able to prepare some memorandum decisions that said that at a minimum, we should give this more time and think this out. At a maximum, we should just bite the bullet and preserve it and do what we can and try to be careful. I mean, you can only spend money for things that—it’s government money. DOE goes to Congress, it’s appropriation and it’s money to x, y, and z. It’s illegal to use it for r, s, and—you know. It’s for this purpose and this purpose only. So it started with, I guess, working with the DOE system and other laws and rules that say, you know, under preservation—there are some preservation responsibilities and others and exploiting those to create room to keep it open until folks could get a better sense of, in general, just the role of the Manhattan Project in history and DOE’s role in preserving that, and working with other institutions, the Park Service and others to formalize that. And of course Park Service is struggling with their own—they don’t have enough money to take care of things they already have. So you get into that whole realm of things. But at least we were able to stop the bulldozers, if you will, or the momentum—the cocooning momentum, at least for B Reactor. Potentially with even T Plant and some other things. And I really give Colleen a lot of credit with how hard she worked, too, to help us put together that strategy and create that opening or stay of execution. [LAUGHTER]Franklin: Did you encounter resistance in Washington, DC for—Klein: Oh, yeah.Franklin: --for this idea? How did you overcome that, to help to show people the value of this?Klein: Well, I guess, fortunately, I had enough—what—backing and credit or chits that I could dissent, disagree with my management agreeably and get things elevated to a higher level. So it was, I think, agree to disagree. And I credit with my management back in DC in the Office of Environmental Management with how they dealt with it too. And letting higher powers basically decide this, with the help of the historian and others. And I think that’s—you know, the other thing that I did is I listened to Skip Gosling. Clay Sell was the deputy secretary at the time. He was a history buff.Franklin: So you say at the time, which—what time was this?Klein: This was at the time when we were struggling with, how do we legitimize preserving B Reactor? Franklin: Do you know around what year or years this would have been?Klein: I’m going to guess it was 2003, 2004 timeframe.Franklin: Okay. Sorry to interrupt.Klein: Yeah, no, I just—so much of this is a blur in terms of who was where when. You start dealing with DC, it’s like—[LAUGHTER]—all look alike after a while. You know, I can come at it from different angles, Republicans, Democrats, you know, different folks’ emphasis and so forth. So I’m having a hard time recalling who exactly that was. But I remember Clay Sell and I can easily get back to you on when that was.Franklin: It’s okay. I was just trying to get a general sense. So you said Skip Gosling?Klein: Skip Gosling was the historian that we were working with. Clay Sell was the Deputy Secretary of Energy that was a history buff and who, I think, just, in the end, prevailed and was a decision-maker that enabled preserving this and working with Park Service. Colleen and I had a few different trips back to DC talking to these people and encouraging them—I hesitate to use the word lobbying, because it means something very, very particular, and we weren’t lobbying Congress; it was really within the Department. Although we had, certainly, allies, I think, with Patty Murray and Doc Hastings and others who, again, appreciated the Hanford history and what was done here and its significance. Franklin: Did the Hanford collection—the array of historic objects and artifacts gathered from Site—was that part of your—what you were in charge of when you were heading the DOE or was that a different—Klein: No, it was—I mean, that was under my purview. And we certainly had staff. But I must confess that of all the alligators that were surrounding the boat, that was the least of my—it wasn’t high up. I mean, that wasn’t—just too many other things were chomping at me and having to deal with. But I always felt comfortable—I mean, when you get in these positions, you kind of look at what your people are doing and you trust them in doing the right thing and you try to set a tone and direction and values and that sort of thing. So I was very fortunate—we have a very competent staff in environmental analysis and preservation, conservation. Paid attention to the different rules and governing those things. And they took care of it. They were, I think, good stewards.Franklin: Great. How did you become involved with the REACH Museum?Klein: Ah! At first it was as an ex oficio member of—it was called the REACH Board at the time. I think Colleen actually suggested it to me and them and set that up. I mean, it was an easy fit for me. As long as I was with DOE, I couldn’t be an actual member of the board. So the job was more of advisory and helping them. Of course, by that time, I think my feelings were well known that I did have a soft spot for appreciating the heritage here. Even predating the Manhattan Project, going back to the basalt flows and then the Ice Age Floods. There’s something very special and unique about this area, both the land and the people. And it’s those circumstances and things that gave rise to—I mean, the geology and the setting here is what gave rise to this being a great location for the Manhattan Project and the plutonium production mission. Which in turn brought all these incredible people here and formed a national laboratory that’s self-sustaining and a wonderful thing in its own right. And now lands are getting turned over to the port and being made available for other uses. I think it opens up opportunities for the tribes. But anyway, so the REACH was an easy fit for me to get involved in. And I’m proud to say I’m still—now I’m one what’s called the Foundation. It’s how the management structure of the REACH is set up. But they’ve overcome some very big hurdles. But I think the fact they have is—it’s meant to be, and it’s going to grow and prosper. But we still have some heavy lifts. Franklin: Okay. Is there—sorry. What would you like future generations to know about working at Hanford? Or just Hanford in general?Klein: I guess I’d like future generations to appreciate both the sacrifice and the significance of what happened here. That goes back to the tribes and what they sacrificed to what the early settlers that were evicted sacrificed, what the men and women involved in the construction, design, that relocated out here sacrificed, and the significance being with what was done. I’m still in awe. B Reactor up and running from nothing to up and running in 18 months, come on! I mean, it’s just—without computers and slide rules. These were adventurers, technologically, engineering, scientifically, and even management-wise. People come together. And at the same time, this is all under—because of threat of war. And creating something where people came and did this remarkable thing and have it used to kill people. There’s so many conflicting things about this to be learned so we don’t repeat the lessons of the past, yet showing what we’re capable of doing when we do come together with enough motivation and incentive and liberties. It’s just remarkable. So it’s a tough one to answer, what do you want people to remember? I just hope they appreciate the whole thing. The sacrifice and the significance.Franklin: Great. Is there anything else that we haven’t talked about that you’d like to mention?Klein: I feel drained. [LAUGHTER] If there’s something in particular that you’re interested in. Yeah, no, I just feel like I’ve been spouting out all over the place here.Franklin: No, it was great. You really touched on a lot of really pertinent topics and it’s really nice to have your interview next to Mike Lawrence—you know, just this kind of documenting this post-production change. I think it’ll be really crucial to help people figure out—this is all part of the same story, and how people figure out, okay, what happened when that singular mission was kind of over, and how did this place kind of find its identity after that, that the whole mission had changed. So thank you. And thank you for talking to us today.Klein: Well, I’m just—it comes back, like the STEM identity. I’m just hoping and optimistic that we can have a future that’s as distinctive and worthy as the significance of our predecessors did out here. Because it really changed the world, when you—it really is mind-blowing in a lot of respects. I’m just grateful to have the opportunity to be a little part of that continuum. Yeah, the fastest eight years of my life. [LAUGHTER]Franklin: Well, thank you, Keith. I really appreciate it.Klein: Yeah, you bet, Robert."

-- list of tags we are looking for
local status, err = pcall(function ()
TAGS = {
  "100 Area",
  "100 F Area",
  "100 N Area",
  "100-B Area",
  "100-B Reactor",
  "100-C Area",
  "100-D Reactor",
  "100-DR",
  "100-F Area",
  "100-F Area Reactor",
  "100-H",
  "100-H Area",
  "100-K Area",
  "100-N Area",
  "101 Building",
  "105 Building",
  "105 C Reactor",
  "105 K-East",
  "105 K-West",
  "109 Building",
  "1100 Area",
  "1100 Building",
  "1703 D Building",
  "184 Building",
  "184 steam power plants",
  "1917-1963",
  "1954",
  "1955",
  "2-East Area",
  "200 Area",
  "200 East",
  "200 East Area",
  "200 West Area",
  "200-East Area",
  "2101 Building",
  "221-T",
  "221-T Plant",
  "222-S", ---------------------------------------
  "222-S Laboratory",
  "222-T Plant",
  "222-V Plant",
  "224 Building",
  "225-B", ---------------------------------------
  "225 B Encapsulation Building",
  "231-Z building",
  "234-5 Area",
  "234-5 building",
  "234-5 Building (Plutonium Finishing Plant)",
  "271 Canyon",
  "300 Area",
  "3000 Area",
  "305 Area",
  "305 Building",
  "306 Building",
  "308 Lab",
  "313 Building",
  "321 Building",
  "324 Building",
  "325 Building",
  "327 Building",
  "329 Building",
  "330-233B Area",
  "3760 Building",
  "3706 Building",
  "3707 Building",
  "3760 Building",
  "400 Area",
  "400 Area / Fast Flux Test Facility",
  "700 Area",
  "703 Building",
  "716 Building",
  "762 Building",
  "Activities",
  "Ad Building",
  "Administrative agencies",
  "Adults",
  "Advertisements",
  "Advertising",
  "Aerial photographs",
  "Aerial views",
  "Agricultural equipment",
  "Airplanes",
  "Alcoholic beverages",
  "Anniversaries",
  "Announcements",
  "Arco",
  "Assistance",
  "Athletes",
  "Atlantic Richfield Co.",
  "Atomic bombs",
  "Atomic Energy Commission",
  "Atomic Heritage Foundation",
  "Audiences",
  "Automobiles",
  "Awards",
  "Axes",
  "B Area",
  "B Plant",
  "B Plant WESF",
  "B Reactor",
  "B Reactor Museum Association",
  "BRMA",
  "Backyards",
  "Baked products",
  "Backers",
  "Balloons (Novelties)",
  "Band Uniforms",
  "Bandages",
  "Bands",
  "Banquets",
  "Barges",
  "Barracks",
  "Baseball",
  "Baseball Player",
  "Bathing suits",
  "Baton twirling",
  "Battelle",
  "Battelle (Wash.)",
  "Beauty contestants",
  "Beauty contests",
  "Bechtel",
  "Bechtel Hanford",
  "Beer",
  "Benches",
  "Beverages",
  "Bicycles",
  "Boats",
  "Bodies of water",
  "Boeing",
  "Boiling Water Reactor",
  "Bouqets",
  "Bricks",
  "Brickwork",
  "Bridges",
  "Broncos",
  "BU reactor",
  "Building 100F",
  "Building 200 East",
  "Building 200 West",
  "Building 325",
  "Building 3706",
  "Building 703",
  "Bulls",
  "Bus terminals",
  "Buses",
  "Business districts",
  "C Area",
  "C Reactor",
  "Cable railroads",
  "Cakes",
  "Cancer",
  "Car washes",
  "Cats",
  "Cattle",
  "Cattle herding",
  "Celebrations",
  "ceremonies",
  "Charitable organizations",
  "Cheney (Wash.)",
  "Chernobyl Nuclear Accident",
  "Children",
  "Christianity",
  "Churches",
  "CIA",
  "Cities and towns",
  "City Planning",
  "Cityscapes",
  "Civic leaders",
  "Civilian Conservation Corps",
  "Clerks",
  "Clinics",
  "Clouds",
  "Clowns",
  "Cobblestone streets",
  "Cold War",
  "Commemorations",
  "Commercial streets",
  "Connell (Wash.)",
  "Construction",
  "Construction camps",
  "Construction workers",
  "Containers",
  "Contests",
  "Conversation",
  "Cooks",
  "Corrals",
  "Costumes",
  "Coyboys",
  "Cowgirls",
  "Cows",
  "Coyote Pumping Plant",
  "Crosswalks",
  "Crowds",
  "D and DR Reactors",
  "D Area",
  "D Plant",
  "D Reactor",
  "Dams",
  "Dance",
  "Dance parties",
  "Dancers",
  "Dash 5 Building",
  "Dash 5 Plant",
  "Dash-5 Building",
  "Department of Energy",
  "Department stores",
  "Deserts",
  "Desks",
  "Dikes (Engineering)",
  "Diners (Restaurants)",
  "Dinner parties",
  "Dirt roads",
  "Disasters",
  "Discussion",
  "DR Area",
  "DR Reactor",
  "Dresses",
  "drinking",
  "Drums (Musical instruments)",
  "Dunes",
  "DuPont",
  "Dwellings",
  "Eating",
  "Effluent Treatment Facility",
  "Eisenhower, Dwight D.",
  "Eltopia (Wash.)",
  "Embankments",
  "Energy Communities Alliance (ECA)",
  "Energy Northwest",
  "Engineering Test Reactor",
  "Entertainment",
  "Envelopes",
  "Environmental Protection Agency (EPA)",
  "Erosion protection works",
  "Evening gowns",
  "Events",
  "F Area",
  "F Reactor",
  "Factories",
  "Farming",
  "Fast Flux Test Facility",
  "Fast Flux Test Facility (FFTF)",
  "Fast Flux Test Facility (Wash.)",
  "FBI",
  "Fences",
  "Fire engines",
  "Fire prevention",
  "Fishing",
  "Flag bearers",
  "Flags",
  "Fliers (Printed matter)",
  "Floats (Parades)",
  "Flood",
  "Flood control",
  "Floods",
  "Flowers",
  "Food storage buildings",
  "Fraternal lodges",
  "Fraternal organizations",
  "Fuels and Materials Exam Facility",
  "Fund raising",
  "General Electric",
  "General stores",
  "General Telephone",
  "GESA (General Electric Supervisors Association)",
  "Government employees",
  "Grains",
  "Grandstands",
  "Group portrait",
  "Group portraits",
  "H Area",
  "H Reactor",
  "HAMMER",
  "HAMMER Site",
  "Hand tools",
  "Hanford",
  "Hanford (Wash.)",
  "Hanford Nuclear Site (Wash.)",
  "Hanford Site (Wash.)",
  "Hanford Waste Vitrification Plant (Wash.)",
  "HAPO (Hanford Atomic Products Operations)",
  "Hay",
  "Haystacks",
  "Health care",
  "Health care personnel",
  "Helicopters",
  "Henry Kaiser",
  "High Temperature Lattice Test Reactor",
  "Historic Buildings",
  "Horseback riding",
  "Horses",
  "Hotels",
  "Houses",
  "Housing",
  "Housing developments",
  "Hunting",
  "Hydroelectric power",
  "Ice Skating",
  "Industrial facilities",
  "Infants",
  "injuries",
  "Joe Soldat",
  "John F. (John Fitzgerald)",
  "K Area",
  "K Basins",
  "K Reactor",
  "K West Reactor",
  "K-Basins",
  "K-East and K-West Reactors",
  "K-West Area",
  "K-West Reactor",
  "KE Area",
  "Kennedy",
  "Kennewick",
  "Kennewick (Wash.)",
  "KW-Basin Sludge Treatment Project",
  "Labor housing",
  "Labor unions",
  "Levees",
  "Livermore",
  "Loading docks",
  "Local Teams",
  "Lodges",
  "Logs",
  "Los Alamos",
  "Manhattan Project",
  "Marching bands",
  "Markets",
  "Masonic buildings",
  "Mass transit",
  "Medical equipment",
  "Medical offices",
  "Meetings",
  "Memorial rites",
  "Military uniforms",
  "Mission Support Alliance",
  "Mists",
  "Mobile homes",
  "Model airplanes",
  "Money",
  "Mountain railroads",
  "Mountain roads",
  "Mountains",
  "N Area",
  "N Reactor",
  "NASA",
  "Neighborhoods",
  "Newspapers",
  "Nuclear reactors",
  "Nuclear Regulatory Commission",
  "Nuclear waste disposal",
  "Nuclear weapons",
  "Nurses",
  "Nursing",
  "Oakridge",
  "Office workers",
  "Offices",
  "Older people",
  "Organizations",
  "outdoor cookery",
  "Pacific Northwest National Laboratory",
  "Pacific Pwer and Light Company",
  "Pageants",
  "Pagers",
  "Parades",
  "Parker, Herb 1910-1984",
  "Parking",
  "Parking lots",
  "Parks",
  "Parties",
  "Pasco (Wash.)",
  "Passes (Landforms)",
  "Pedestrians",
  "PFP plant",
  "Picnic grounds",
  "Picnics",
  "Piers",
  "Pines",
  "Pitchforks",
  "Play (Recreation)",
  "Plutonium",
  "Plutonium Finishing Plant",
  "Plutonium Recycle Test Reactor (PRTR)",
  "Plutonium Uranium Extraction Plant (PUREX)",
  "Podiums",
  "Political campaigns",
  "Political elections",
  "Political participation",
  "Posing",
  "Posters",
  "Prefabricatd houses",
  "Priest Rapids Power Plant",
  "processions",
  "Protestant Churches",
  "Public Schools",
  "Public service",
  "Public service organizations",
  "Public speaking",
  "PUREX",
  "PUREX 200 East Area",
  "Quonset huts",
  "Rafts",
  "Railroad bridges",
  "Railroad cars",
  "Railroad tracks",
  "Railroad trains",
  "Railroads",
  "Reduction-Oxidation Plant (REDOX)",
  "Religion",
  "Religious orders",
  "Reservoirs",
  "Residential streets",
  "Retirements",
  "Reviewing stands",
  "Rivers",
  "Roads",
  "Rodeos",
  "Ron Kathren",
  "Running",
  "Safety",
  "Sandboils",
  "Savannah River",
  "Schools",
  "SCRAM",
  "Secrecy",
  "Shopping",
  "Shopping centers",
  "Sick persons",
  "Signs (Notices)",
  "Silhouettes",
  "Silos",
  "Singers",
  "Skyscrapers",
  "Slogans",
  "Sombreros",
  "Spectators",
  "Spillways",
  "Spirtual life",
  "Splints (Surgery)",
  "Sports",
  "Stadiums",
  "Stages (Platforms)",
  "Steeples",
  "Stilts",
  "Stores",
  "Street lights",
  "Street railroad tracks",
  "Street railroads",
  "Streets",
  "Suits (Clothing)",
  "Sun",
  "Sunnyside (Wash.)",
  "Sunrises",
  "sunsets",
  "supplies",
  "swimming",
  "T Plant",
  "Tables",
  "Tank Farms",
  "Teams",
  "Theaters",
  "Tipis",
  "Toilets",
  "town life",
  "Tractors",
  "Trailers",
  "Transportation",
  "Transportation facilities",
  "Trash cans",
  "Trees",
  "Trestles",
  "Tricycles",
  "Trousers",
  "Trucks",
  "Tugboats",
  "Typewriters",
  "U Plant",
  "Uniforms",
  "United Nuclear Corporation",
  "United States. Bureau of Reclamation",
  "Vehicles",
  "Violoncellos",
  "Vit Plant",
  "Vitrification Plant",
  "Volleyball",
  "Walla Walla (Wash.)",
  "War",
  "War bonds and funds",
  "War Relocation Authority (United States)",
  "War work",
  "Washington Public Power Supply System",
  "Washington Public Power Supply System (WPPSS)",
  "Waste Vitrification Plant",
  "Waterways",
  "Waterworks",
  "Western Electric",
  "Westinghouse",
  "wharves",
  "White Bluffs (Wash.)",
  "White Bluffs Bank",
  "Wounds",
  "Yachts",
  "Yackima (Wash.)",
  "Yards",
  "Z Plant",
  "Zillah (Wash.)"
} end)





-- Do not modify anything after this point ---------------------------------

FOUNDYEARS = {}
FOUNDTAGS  = {}
STR        = ""

-- most of these are in plurarl so add all NON plural also
for i=1, #TAGS do
  local lastChar = string.sub(TAGS[i], string.len(TAGS[i]))
  local lastTwoChars = string.sub(TAGS[i], string.len(TAGS[i])-1, string.len(TAGS[i]))
  if (lastChar == "s" and lastTwoChars ~= "es") then
    table.insert(TAGS, #TAGS+1, string.sub(TAGS[i], 1, string.len(TAGS[i])-1))
  end
  -- working this part out..
  --[[
  if (lastTwoChars == "es") then
    for j=1, #esExceptions do
      if (esExceptions[j] ~= TAGS[i]) then
        table.insert(TAGS, #TAGS+1, string.sub(TAGS[i], 1, string.len(TAGS[i])-2))
      end
    end
  end
  ]]
end

for i=1, #TAGS do
  if string.find(text, TAGS[i]) ~= nil then
    table.insert(FOUNDTAGS, #FOUNDTAGS+1, TAGS[i])
  end
end
if (#FOUNDTAGS>0) then
  print("Found these tags:")
else
  if text~="" then
    print("No tags found!")
  else
    print('Please make sure the \ntext = ""\n(at the top) is filled out!')
  end
end

for i=1, #FOUNDTAGS do
  if FOUNDTAGS[i] ~= "" then
    if i~=#FOUNDTAGS then
      STR = STR .. FOUNDTAGS[i] .. SEPARATOR_CHARACTER
    else
      STR = STR .. FOUNDTAGS[i]
    end
  end
end

print(STR)





